name: Conditional Secret Access
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-user:
    runs-on: ubuntu-latest
    outputs:
      is-trusted: ${{ steps.check-user.outputs.is-trusted }}
    steps:
      - name: Check if user is trusted
        id: check-user
        run: |
          TRUSTED_USERS='["trusted-user1", "trusted-user2", "trusted-user3"]'
          if echo "$TRUSTED_USERS" | jq -e --arg user "${{ github.actor }}" 'index($user) != null' > /dev/null; then
            echo "is-trusted=true" >> $GITHUB_OUTPUT
          else
            echo "is-trusted=false" >> $GITHUB_OUTPUT
          fi

  test-with-secrets:
    needs: check-user
    if: needs.check-user.outputs.is-trusted == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Use secret
        run: |
          echo "Secret: ${{ secrets.MY_SECRET }}"
