name: Secure Secret Access
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  verify-user:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR from fork
        run: |
          echo "This workflow runs in fork context - NO SECRET ACCESS"
          echo "But it completes successfully to trigger the next workflow"
