name: User-based Secret Access
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if user is allowed (using secret)
        id: check-access
        run: |
          # Check if current user is in the allowed list from SECRET
          if [[ ",${{ secrets.ALLOWED_USERS }}," == *",${{ github.actor }},"* ]]; then
            echo "access_granted=true" >> $GITHUB_OUTPUT
          else
            echo "access_granted=false" >> $GITHUB_OUTPUT
          fi

      - name: Use secret for allowed users
        if: steps.check-access.outputs.access_granted == 'true'
        run: |
          echo "✅ User ${{ github.actor }} has secret access"
          echo "Secret is set: ${{ secrets.MY_SECRET != '' }}"
          echo "Running secure operation with secret..."
        
      - name: Regular test for others
        if: steps.check-access.outputs.access_granted == 'false'
        run: |
          echo "⚠️  User ${{ github.actor }} has no secret access"
          echo "Running without secrets"
