name: Secure Secret Access
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  verify-user:
    runs-on: ubuntu-latest
    outputs:
      user-allowed: ${{ steps.verify.outputs.user-allowed }}
    steps:
      - name: Verify user against allowlist
        id: verify
        run: |
          ALLOWED_USERS="auslin-aot,trusted-user-2,trusted-user-3"
          if [[ ",$ALLOWED_USERS," == *",${{ github.actor }},"* ]]; then
            echo "user-allowed=true" >> $GITHUB_OUTPUT
          else
            echo "user-allowed=false" >> $GITHUB_OUTPUT
          fi

